-- FIX: Consider changing this to a normal module instead of a static. This is unnecessarily complicated for the LSP
-- which does not give satisfactory results because of this. How would it affect the performance? <30-03-25>
_G.static = {}
-- FIX: Use codicon for this. It is easy to find with Snacks icon picker (keymap `,si`) <25-06-25>
_G.static.icons = {
  telescope = '',
  link = '',
  rocket = '',
  quote = '',
  find = '',
  projects = '',
  terminal = '',
  macro_recording = '',
  spellcheck = '',
  ActiveLSP = '',
  ActiveTS = '',
  ellipsis = '…',
  ai = '',
  snippets = '',
  sessions = '󰒲',
  arrow = {
    left = '',
    right = '',
  },
  dap = {
    --     
    breakpoint = '',
    breakpoint_condition = '',
    breakpoint_rejected = '',
    log_point = '.>',
    stopped = '',
  },
  fold = {
    closed = '',
    opened = '',
    separator = ' ',
  },
  explorer = {
    folder_closed = '',
    folder_empty = '',
    folder_move = '',
    folder_open = '',
  },
  comments = {
    todo = '',
    note = '',
    hack = '',
    performance = '',
    bug = '',
  },
  diagnostics = {
    diagnostics = '', -- ''
    Error = '',
    Warn = '',
    Hint = '',
    Info = '',
  },
  lsp = {
    lsp = '',
    loading_1 = '',
    loading_2 = '',
    loading_3 = '',
    loaded = '',
    unavailable = '',
    enabled = ' ',
    disabled = ' ',
    attached = '󰖩 ',
    kinds = {
      Array = ' ',
      Boolean = '󰨙 ',
      Class = ' ',
      Color = ' ',
      Control = ' ',
      Collapsed = ' ',
      Constant = '󰏿 ',
      Constructor = ' ',
      Copilot = ' ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = ' ',
      File = ' ',
      Folder = ' ',
      Function = '󰊕 ',
      Interface = ' ',
      Key = ' ',
      Keyword = ' ',
      Method = '󰊕 ',
      Module = ' ',
      Namespace = '󰦮 ',
      Null = ' ',
      Number = '󰎠 ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Property = ' ',
      Reference = ' ',
      Snippet = '󱄽 ',
      String = ' ',
      Struct = '󰆼 ',
      Text = ' ',
      TypeParameter = ' ',
      Unit = ' ',
      Unknown = ' ',
      Value = ' ',
      Variable = '󰀫 ',
    },
  },

  git = {
    commit = '󰜘', -- used by git log
    added = '',
    deleted = '',
    ignored = ' ',
    modified = '○',
    unmerged = ' ',
    untracked = '?',
    --  ,  
    label = ' ',
    issue = ' ',
    review = ' ',
    user = ' ',
    fork = ' ',
    git = ' ',
    add = ' ',
    branch = ' ',
    change = ' ',
    conflict = ' ',
    delete = ' ',
    -- ignored = '◌',
    pull_request = ' ',
    merge = ' ',
    renamed = ' ',
    staged = '✓',
    unstaged = '✗',
    github = ' ',
    -- untracked = '★',
  },
  fileformat = {
    dos = '',
    mac = '',
    unix = '',
    unknown = '',
  },
  statusline = {
    separators = {
      rangle = '⟩',
      langle = '⟨',
    },
    linenumber = '',
    modified = '', -- ,פֿ
    readonly = '', -- ,,,
  },
  undotree = {
    node = '',
  },
}

static.icons.cmp = {
  Env = ' ',
  LazyDev = '󰒲 ',
  Buffer = static.icons.find .. ' ',
  LSP = static.icons.lsp.lsp .. ' ',
  Snippets = static.icons.snippets .. ' ',
  git = static.icons.git.github .. ' ',
  latex_symbols = '󰂡 ',
  LaTeX = '󰂡 ',
  Ripgrep = '󰭎 ',
  spell = static.icons.spellcheck .. ' ',
  ai = static.icons.ai .. ' ',
  CodeCompanion = static.icons.ai .. ' ',
  path = static.icons.explorer.folder_open .. ' ',
  digraphs = ' ',
  ['Words Thesaurus'] = ' ',
  ['Words Dictionary'] = ' ',
  ['Conventional Commits'] = static.icons.git.github .. ' ',
}
